import { ArtifactData, ArtifactType } from './ArtifactPanel';
import { supabase } from '@/integrations/supabase/client';

/**
 * Detects if AI response should generate an artifact
 */
export function detectArtifactFromResponse(userQuery: string, aiResponse: string): ArtifactData | null {
  const lower = userQuery.toLowerCase();

  // Trading Journal queries
  if (hasJournalPattern(lower)) {
    return parseJournalArtifact(aiResponse, userQuery);
  }

  // Screener / stock results
  if (hasScreenerPattern(lower) && hasTableData(aiResponse)) {
    return parseScreenerArtifact(aiResponse, userQuery);
  }

  // Financial statement queries
  if (hasFinancialPattern(lower)) {
    return null; // Will be generated by fetchFinancialStatement
  }

  // Chart / technical analysis
  if (hasChartPattern(lower) && hasTechnicalData(aiResponse)) {
    return parseChartArtifact(aiResponse, userQuery);
  }

  // Relationship / analysis with multiple entities
  if (hasRelationshipPattern(aiResponse)) {
    return parseRelationshipArtifact(aiResponse, userQuery);
  }

  return null;
}

/**
 * Fetch detailed financial statements from TradingView via screener
 */
export async function fetchFinancialStatement(symbol: string): Promise<ArtifactData | null> {
  try {
    // Determine market from symbol
    const market = symbol.includes(':') ? symbol.split(':')[0].toLowerCase() : 'america';
    const cleanSymbol = symbol.includes(':') ? symbol.split(':')[1] : symbol;

    // Balance Sheet fields
    const balanceSheetCols = [
      'name', 'description', 'close', 'market_cap_basic',
      'total_assets', 'total_liabilities_fq', 'total_equity',
      'total_current_assets', 'total_current_liabilities',
      'cash_n_short_term_invest_fq', 'long_term_debt_fq',
      'total_debt', 'net_debt', 'goodwill_fq',
      'book_value_per_share_fq', 'tangible_book_value_per_share_fq',
    ];

    // Income Statement fields
    const incomeCols = [
      'total_revenue', 'gross_profit_fq', 'operating_income_fq',
      'net_income', 'earnings_per_share_basic_ttm', 'earnings_per_share_diluted_ttm',
      'ebitda', 'gross_margin', 'operating_margin',
      'net_margin', 'revenue_per_share_ttm',
      'revenue_growth_yoy', 'earnings_growth_yoy',
    ];

    // Cash Flow fields
    const cashFlowCols = [
      'cash_f_operating_activities_ttm', 'cash_f_investing_activities_ttm',
      'cash_f_financing_activities_ttm', 'free_cash_flow_ttm',
      'capital_expenditures_ttm', 'dividends_paid_fq',
    ];

    // Ratios
    const ratioCols = [
      'price_earnings_ttm', 'price_book_fq', 'price_sales_current',
      'price_free_cash_flow_ttm', 'enterprise_value_ebitda_ttm',
      'return_on_equity', 'return_on_assets', 'return_on_invested_capital',
      'debt_to_equity', 'current_ratio', 'quick_ratio',
      'dividend_yield_recent', 'payout_ratio',
    ];

    const allColumns = [...balanceSheetCols, ...incomeCols, ...cashFlowCols, ...ratioCols];

    const { data, error } = await supabase.functions.invoke('tv-screener', {
      body: {
        type: 'stock',
        columns: allColumns,
        filters: [],
        sort: { sortBy: 'market_cap_basic', sortOrder: 'desc' },
        range: [0, 5],
        search: cleanSymbol,
        markets: [mapMarket(market)],
      },
    });

    if (error || !data?.data?.length) return null;

    const stock = data.data[0];
    const fmt = (v: any) => v !== null && v !== undefined ? v : null;

    const artifact: ArtifactData = {
      id: Date.now().toString(),
      type: 'financial_statement',
      title: `📋 งบการเงิน ${stock.name || cleanSymbol}`,
      timestamp: new Date(),
      source: `TradingView • ${stock.description || ''}`,
      content: {
        groups: [
          {
            title: '💰 งบดุล (Balance Sheet)',
            headers: ['รายการ', 'มูลค่า'],
            rows: [
              ['สินทรัพย์รวม (Total Assets)', fmt(stock.total_assets)],
              ['หนี้สินรวม (Total Liabilities)', fmt(stock.total_liabilities_fq)],
              ['ส่วนของผู้ถือหุ้น (Equity)', fmt(stock.total_equity)],
              ['สินทรัพย์หมุนเวียน (Current Assets)', fmt(stock.total_current_assets)],
              ['หนี้สินหมุนเวียน (Current Liab.)', fmt(stock.total_current_liabilities)],
              ['เงินสด+ลงทุนระยะสั้น', fmt(stock.cash_n_short_term_invest_fq)],
              ['หนี้ระยะยาว (LT Debt)', fmt(stock.long_term_debt_fq)],
              ['หนี้รวม (Total Debt)', fmt(stock.total_debt)],
              ['หนี้สุทธิ (Net Debt)', fmt(stock.net_debt)],
              ['Goodwill', fmt(stock.goodwill_fq)],
              ['Book Value/Share', fmt(stock.book_value_per_share_fq)],
            ].filter(r => r[1] !== null),
          },
          {
            title: '📊 งบกำไรขาดทุน (Income Statement)',
            headers: ['รายการ', 'มูลค่า'],
            rows: [
              ['รายได้รวม (Revenue)', fmt(stock.total_revenue)],
              ['กำไรขั้นต้น (Gross Profit)', fmt(stock.gross_profit_fq)],
              ['กำไรจากการดำเนินงาน', fmt(stock.operating_income_fq)],
              ['กำไรสุทธิ (Net Income)', fmt(stock.net_income)],
              ['EPS (Basic)', fmt(stock.earnings_per_share_basic_ttm)],
              ['EPS (Diluted)', fmt(stock.earnings_per_share_diluted_ttm)],
              ['EBITDA', fmt(stock.ebitda)],
              ['Gross Margin', fmt(stock.gross_margin) !== null ? stock.gross_margin + '%' : null],
              ['Operating Margin', fmt(stock.operating_margin) !== null ? stock.operating_margin + '%' : null],
              ['Net Margin', fmt(stock.net_margin) !== null ? stock.net_margin + '%' : null],
              ['Revenue Growth YoY', fmt(stock.revenue_growth_yoy) !== null ? stock.revenue_growth_yoy + '%' : null],
              ['Earnings Growth YoY', fmt(stock.earnings_growth_yoy) !== null ? stock.earnings_growth_yoy + '%' : null],
            ].filter(r => r[1] !== null),
          },
          {
            title: '💵 งบกระแสเงินสด (Cash Flow)',
            headers: ['รายการ', 'มูลค่า'],
            rows: [
              ['CFO (Operating)', fmt(stock.cash_f_operating_activities_ttm)],
              ['CFI (Investing)', fmt(stock.cash_f_investing_activities_ttm)],
              ['CFF (Financing)', fmt(stock.cash_f_financing_activities_ttm)],
              ['Free Cash Flow', fmt(stock.free_cash_flow_ttm)],
              ['CapEx', fmt(stock.capital_expenditures_ttm)],
              ['Dividends Paid', fmt(stock.dividends_paid_fq)],
            ].filter(r => r[1] !== null),
          },
          {
            title: '📈 อัตราส่วนทางการเงิน (Ratios)',
            headers: ['รายการ', 'มูลค่า'],
            rows: [
              ['P/E Ratio (TTM)', fmt(stock.price_earnings_ttm)],
              ['P/B Ratio', fmt(stock.price_book_fq)],
              ['P/S Ratio', fmt(stock.price_sales_current)],
              ['P/FCF Ratio', fmt(stock.price_free_cash_flow_ttm)],
              ['EV/EBITDA', fmt(stock.enterprise_value_ebitda_ttm)],
              ['ROE', fmt(stock.return_on_equity) !== null ? stock.return_on_equity + '%' : null],
              ['ROA', fmt(stock.return_on_assets) !== null ? stock.return_on_assets + '%' : null],
              ['ROIC', fmt(stock.return_on_invested_capital) !== null ? stock.return_on_invested_capital + '%' : null],
              ['Debt/Equity', fmt(stock.debt_to_equity)],
              ['Current Ratio', fmt(stock.current_ratio)],
              ['Quick Ratio', fmt(stock.quick_ratio)],
              ['Dividend Yield', fmt(stock.dividend_yield_recent) !== null ? stock.dividend_yield_recent + '%' : null],
              ['Payout Ratio', fmt(stock.payout_ratio) !== null ? stock.payout_ratio + '%' : null],
            ].filter(r => r[1] !== null),
          },
        ],
      },
    };

    return artifact;
  } catch (err) {
    console.error('fetchFinancialStatement error:', err);
    return null;
  }
}

/**
 * Parse screener results into artifact table
 */
function parseScreenerArtifact(response: string, query: string): ArtifactData | null {
  // Try to extract table-like data from response
  const lines = response.split('\n').filter(l => l.includes('|') || l.includes(':'));
  if (lines.length < 3) return null;

  const rows: string[][] = [];
  const headers: string[] = [];

  for (const line of lines) {
    if (line.includes('|')) {
      const cells = line.split('|').map(c => c.trim()).filter(Boolean);
      if (headers.length === 0 && cells.length > 1) {
        headers.push(...cells);
      } else if (cells.length > 1 && !cells.every(c => c.match(/^[-]+$/))) {
        rows.push(cells);
      }
    }
  }

  if (headers.length === 0 || rows.length === 0) return null;

  return {
    id: Date.now().toString(),
    type: 'screener_result',
    title: `🔍 ${query.slice(0, 40)}`,
    timestamp: new Date(),
    source: 'Screener',
    content: { headers, rows },
  };
}

function parseChartArtifact(response: string, query: string): ArtifactData | null {
  // Extract symbol from query
  const symbolMatch = query.match(/\b([A-Z]{2,6}(?:USDT?)?)\b/i);
  const symbol = symbolMatch ? symbolMatch[1].toUpperCase() : 'Unknown';

  // Extract numeric values
  const indicators: Record<string, number> = {};
  const rsiMatch = response.match(/RSI[:\s]*([0-9.]+)/i);
  if (rsiMatch) indicators['RSI'] = parseFloat(rsiMatch[1]);
  const macdMatch = response.match(/MACD[:\s]*([0-9.-]+)/i);
  if (macdMatch) indicators['MACD'] = parseFloat(macdMatch[1]);

  const signals: any[] = [];
  if (response.includes('oversold') || response.includes('ขายมากเกิน')) {
    signals.push({ name: 'Oversold', direction: 'bullish', detail: 'RSI < 30' });
  }
  if (response.includes('overbought') || response.includes('ซื้อมากเกิน')) {
    signals.push({ name: 'Overbought', direction: 'bearish', detail: 'RSI > 70' });
  }
  if (response.includes('golden cross')) {
    signals.push({ name: 'Golden Cross', direction: 'bullish', detail: 'SMA50 > SMA200' });
  }

  return {
    id: Date.now().toString(),
    type: 'chart_analysis',
    title: `📊 ${symbol} Technical Analysis`,
    timestamp: new Date(),
    source: 'Trading Chart',
    content: {
      symbol,
      timeframe: 'Daily',
      indicators: Object.keys(indicators).length > 0 ? indicators : undefined,
      signals: signals.length > 0 ? signals : undefined,
      analysis: extractAnalysisText(response),
    },
  };
}

function parseRelationshipArtifact(response: string, query: string): ArtifactData | null {
  // Detect entities and relationships
  const nodes: any[] = [];
  const connections: any[] = [];

  // Simple entity extraction
  const assetPattern = /\b((?:XAU|BTC|ETH|USD|EUR|GBP|JPY|SPX|DXY|VIX|Gold|Bitcoin|Oil|ทองคำ|น้ำมัน|หุ้น)[A-Z]*)\b/gi;
  const assets = [...new Set(response.match(assetPattern) || [])];
  
  assets.forEach(asset => {
    nodes.push({ label: asset, type: 'asset', category: 'Assets' });
  });

  // Extract event/indicator mentions
  const events = response.match(/(?:Fed|ECB|BOJ|CPI|GDP|NFP|FOMC|PMI|inflation|ดอกเบี้ย|เงินเฟ้อ)[^,.]*/gi) || [];
  events.slice(0, 5).forEach(ev => {
    nodes.push({ label: ev.trim(), type: 'event', category: 'Events & Indicators' });
  });

  if (nodes.length < 2) return null;

  // Create basic connections
  for (let i = 0; i < Math.min(assets.length, 4); i++) {
    for (let j = i + 1; j < Math.min(assets.length, 4); j++) {
      connections.push({
        from: assets[i],
        to: assets[j],
        type: response.includes('inverse') || response.includes('สวนทาง') ? 'negative' : 'positive',
      });
    }
  }

  return {
    id: Date.now().toString(),
    type: 'relationship',
    title: `🔗 ${query.slice(0, 40)}`,
    timestamp: new Date(),
    source: 'AI Analysis',
    content: {
      nodes,
      connections,
      summary: extractAnalysisText(response).slice(0, 300),
    },
  };
}

/* ─── Journal Artifact ─── */

function hasJournalPattern(q: string): boolean {
  return /journal|trading journal|เทรด.*journal|สรุป.*เทรด|ผลการเทรด|win.*rate|p&l|pnl|กำไร.*ขาดทุน|สถิติ.*เทรด|performance|ประสิทธิภาพ|วิเคราะห์.*เทรด|able.*score|psychology|จิตวิทยา|monte.*carlo|r-?multiple|risk.*reward|drawdown|streak|setup.*performance|สรุปผล/i.test(q);
}

function parseJournalArtifact(response: string, query: string): ArtifactData | null {
  // Extract metrics from AI response
  const headers: string[] = [];
  const rows: string[][] = [];
  const groups: { title: string; headers: string[]; rows: string[][] }[] = [];

  // Try to extract table data from response
  const lines = response.split('\n');
  let currentGroup: { title: string; headers: string[]; rows: string[][] } | null = null;

  for (const line of lines) {
    const trimmed = line.trim();
    // Detect section headers
    if (trimmed.startsWith('**') && trimmed.endsWith('**')) {
      if (currentGroup && currentGroup.rows.length > 0) groups.push(currentGroup);
      currentGroup = { title: trimmed.replace(/\*\*/g, ''), headers: [], rows: [] };
      continue;
    }
    // Detect table rows
    if (trimmed.includes('|')) {
      const cells = trimmed.split('|').map(c => c.trim()).filter(Boolean);
      if (cells.length > 1 && !cells.every(c => /^[-:]+$/.test(c))) {
        if (currentGroup) {
          if (currentGroup.headers.length === 0) currentGroup.headers = cells;
          else currentGroup.rows.push(cells);
        } else {
          if (headers.length === 0) headers.push(...cells);
          else rows.push(cells);
        }
      }
    }
    // Detect key-value pairs like "Win Rate: 65%"
    const kvMatch = trimmed.match(/^[•\-]\s*(.+?):\s*(.+)$/);
    if (kvMatch && currentGroup) {
      if (currentGroup.headers.length === 0) currentGroup.headers = ['Metric', 'Value'];
      currentGroup.rows.push([kvMatch[1], kvMatch[2]]);
    }
  }
  if (currentGroup && currentGroup.rows.length > 0) groups.push(currentGroup);

  // If no structured data found, create from numbered items
  if (groups.length === 0 && rows.length === 0) {
    const bulletLines = lines.filter(l => /^[\d]+[.)]\s|^[-•]\s/.test(l.trim()));
    if (bulletLines.length >= 2) {
      groups.push({
        title: '📊 Trading Journal Analysis',
        headers: ['#', 'Detail'],
        rows: bulletLines.map((l, i) => [
          String(i + 1),
          l.replace(/^[\d]+[.)]\s|^[-•]\s/, '').trim()
        ])
      });
    }
  }

  if (groups.length === 0 && rows.length === 0) return null;

  return {
    id: Date.now().toString(),
    type: 'table',
    title: `📔 ${query.slice(0, 50)}`,
    timestamp: new Date(),
    source: 'Trading Journal',
    content: groups.length > 0 ? { groups } : { headers, rows },
    aiResponse: response,
    userQuery: query,
  };
}

/* ─── Helpers ─── */

function hasScreenerPattern(q: string): boolean {
  return /หาหุ้น|screener|scan|top.*gain|oversold|strong.*buy|breakout|volume|สแกน|หุ้นที่น่า|dividend|ปันผล|value.*stock/i.test(q);
}

function hasFinancialPattern(q: string): boolean {
  return /งบการเงิน|financial.*statement|balance.*sheet|income.*statement|cash.*flow|งบดุล|งบกำไร|อัตราส่วน.*การเงิน|financial.*report|ดูงบ|pull.*financial/i.test(q);
}

function hasChartPattern(q: string): boolean {
  return /chart|กราฟ|technical|RSI|MACD|วิเคราะห์.*เทค|analysis.*chart|แนวรับ|แนวต้าน|support|resistance/i.test(q);
}

function hasTableData(text: string): boolean {
  return (text.match(/\|/g) || []).length > 5;
}

function hasTechnicalData(text: string): boolean {
  return /RSI|MACD|SMA|EMA|Bollinger|ATR|volume|signal/i.test(text);
}

function hasRelationshipPattern(text: string): boolean {
  const assetCount = (text.match(/\b(?:XAU|BTC|ETH|USD|EUR|Gold|Bitcoin|Oil|VIX|DXY|SPX|ทองคำ|หุ้น)\b/gi) || []).length;
  return assetCount >= 3;
}

function extractAnalysisText(response: string): string {
  // Get the analysis section
  const analysisIdx = response.indexOf('การวิเคราะห์');
  if (analysisIdx > -1) return response.slice(analysisIdx).slice(0, 500);
  
  const sections = response.split('---');
  return (sections[sections.length - 1] || response).trim().slice(0, 500);
}

function mapMarket(market: string): string {
  const map: Record<string, string> = {
    nasdaq: 'america', nyse: 'america', set: 'thailand', bkk: 'thailand',
    hkex: 'hongkong', tsx: 'canada', lse: 'uk',
  };
  return map[market] || market || 'america';
}
